version: '3.4'

services:
  powerposition:
    image: ${DOCKER_REGISTRY-}powerposition
    environment:
      - CRON_ConsoleSettings__OutputString=NewTestString
    build:
      context: .
      dockerfile: Dockerfile